
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace PremierLigML_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            PremierLigML.ModelInput sampleData = new PremierLigML.ModelInput()
            {
                HomeTeam = @"Crystal Palace",
                AwayTeam = @"Southampton",
                FTHomeGol = 1F,
                FTAwayGol = 0F,
                AwayShot = 9F,
                HomeCorner = 7F,
                AwayCorner = 3F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = PremierLigML.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual HomeShot with predicted HomeShot from sample data...\n\n");


            Console.WriteLine($"HomeTeam: {@"Crystal Palace"}");
            Console.WriteLine($"AwayTeam: {@"Southampton"}");
            Console.WriteLine($"FTHomeGol: {1F}");
            Console.WriteLine($"FTAwayGol: {0F}");
            Console.WriteLine($"HomeShot: {5F}");
            Console.WriteLine($"AwayShot: {9F}");
            Console.WriteLine($"HomeCorner: {7F}");
            Console.WriteLine($"AwayCorner: {3F}");


            Console.WriteLine($"\n\nPredicted HomeShot: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
